# Site settings
title: "Code Salad"
email: davidcollins4481@gmail.com
description: "Just a place to write code and play."
baseurl: ""
url: "http://davidcollins4481.github.io"
#twitter_username: jekyllrb
github_username:  davidcollins4481

# Build settings
markdown: kramdown
permalink: pretty
